services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "@GGDjhJAbdcidi232ds"
      ACCEPT_EULA: "Y"
    networks:
      - mynetwork

  webapi:
    build:
      context: .
      dockerfile: Coin.Api/Dockerfile
    container_name: webapi
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      NbpApi__BaseUrl: "https://api.nbp.pl/"
      ConnectionStrings__DbConnection: "Server=sqlserver,1433;Database=Coin;User=sa;Password=@GGDjhJAbdcidi232ds;TrustServerCertificate=True;"
    networks:
      - mynetwork

networks:
  mynetwork: